export enum Perfil {
  ADMIN = 'ADMIN',
  FINANCEIRO = 'FINANCEIRO',
  APROVADOR = 'APROVADOR',
  GESTOR = 'GESTOR',
  AUDITOR = 'AUDITOR',
  VISUALIZADOR = 'VISUALIZADOR',
  COLABORADOR = 'COLABORADOR',
}

export enum StatusCP {
  PENDENTE = 'PENDENTE',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  APROVADO = 'APROVADO',
  PAGO = 'PAGO',
  CANCELADO = 'CANCELADO',
  VENCIDO = 'VENCIDO',
}

export enum StatusCR {
  PENDENTE = 'PENDENTE',
  RECEBIDO = 'RECEBIDO',
  VENCIDO = 'VENCIDO',
  CANCELADO = 'CANCELADO',
}

export enum OrigemLancamento {
  MANUAL = 'MANUAL',
  IMPORTACAO_OFX = 'IMPORTACAO_OFX',
  WHATSAPP = 'WHATSAPP',
  UPLOAD_WEB = 'UPLOAD_WEB',
  CONTRATO = 'CONTRATO',
  VIAGEM = 'VIAGEM',
}

export enum StatusPreLancamento {
  RASCUNHO = 'RASCUNHO',
  PENDENTE_APROVACAO = 'PENDENTE_APROVACAO',
  APROVADO = 'APROVADO',
  REJEITADO = 'REJEITADO',
}

export enum TipoDespesa {
  TRANSPORTE = 'TRANSPORTE',
  HOSPEDAGEM = 'HOSPEDAGEM',
  ALIMENTACAO = 'ALIMENTACAO',
  SERVICO = 'SERVICO',
  PRODUTO = 'PRODUTO',
  OUTROS = 'OUTROS',
}

export enum Recorrencia {
  UNICA = 'UNICA',
  SEMANAL = 'SEMANAL',
  QUINZENAL = 'QUINZENAL',
  MENSAL = 'MENSAL',
  TRIMESTRAL = 'TRIMESTRAL',
  SEMESTRAL = 'SEMESTRAL',
  ANUAL = 'ANUAL',
}

export enum StatusViagem {
  SOLICITADA = 'SOLICITADA',
  APROVADA_GESTOR = 'APROVADA_GESTOR',
  APROVADA_FINANCEIRO = 'APROVADA_FINANCEIRO',
  ADIANTAMENTO_LIBERADO = 'ADIANTAMENTO_LIBERADO',
  EM_VIAGEM = 'EM_VIAGEM',
  PRESTACAO_PENDENTE = 'PRESTACAO_PENDENTE',
  PRESTACAO_ENVIADA = 'PRESTACAO_ENVIADA',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
}

export enum TipoContrato {
  CLIENTE = 'CLIENTE',
  FORNECEDOR = 'FORNECEDOR',
}

export enum IndiceReajuste {
  IPCA = 'IPCA',
  IGPM = 'IGPM',
  INPC = 'INPC',
  PERCENTUAL_FIXO = 'PERCENTUAL_FIXO',
  SEM_REAJUSTE = 'SEM_REAJUSTE',
}

export enum TipoEmprestimo {
  TOMADO = 'TOMADO',
  CONCEDIDO = 'CONCEDIDO',
}

export enum SistemaAmortizacao {
  PRICE = 'PRICE',
  SAC = 'SAC',
}

export enum TipoImposto {
  IRPJ = 'IRPJ',
  CSLL = 'CSLL',
  PIS = 'PIS',
  COFINS = 'COFINS',
  ICMS = 'ICMS',
  ISS = 'ISS',
  INSS = 'INSS',
  FGTS = 'FGTS',
  SIMPLES_NACIONAL = 'SIMPLES_NACIONAL',
  OUTRO = 'OUTRO',
}

export enum RegimeTributario {
  SIMPLES_NACIONAL = 'SIMPLES_NACIONAL',
  LUCRO_PRESUMIDO = 'LUCRO_PRESUMIDO',
  LUCRO_REAL = 'LUCRO_REAL',
}

export enum TipoNotificacao {
  APROVACAO_PENDENTE = 'APROVACAO_PENDENTE',
  VENCIMENTO_PROXIMO = 'VENCIMENTO_PROXIMO',
  CONTRATO_EXPIRANDO = 'CONTRATO_EXPIRANDO',
  ALERTA_FLUXO = 'ALERTA_FLUXO',
  SISTEMA = 'SISTEMA',
}
